apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: simulado-backend
        image: rmatiello/simulado-backend:1.0.1
        ports:
        - containerPort: 8080       
        env:
        - name: spring.data.mongodb.host
          value: "my-lb-mongo"