apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostNetwork: true
      containers:
      - name: simulado-frontend
        image: rmatiello/simulado-frontend:1.0.1
        ports:
        - containerPort: 80
          